# Site settings
title: "Lokesh Dammalapati"
description: "Data Science Portfolio"
logo: "/assets/profile.jpg"  # Profile image path
remote_theme: "mmistakes/minimal-mistakes"

# Navigation (One-Page Scroll Links)
header_pages: []

# Plugins
plugins:
  - jekyll-include-cache
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-archives
  - jekyll-paginate
  - jekyll-remote-theme
  - jekyll-include-cache  

# Custom Styling (CSS)
custom_css: "/assets/style.css"

# Footer settings
footer:
  links:
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/LokeshChowdary1999"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://linkedin.com/in/lokeshd1999"
